Belt/BeltExam/Models/Coupon.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BeltExam.Models;

public class Coupon
{
    [Key]
    public int CouponId { get; set; }

    [Required(ErrorMessage = "is required")]
    [Display(Name = "Coupon Code")]
    public string CouponCode { get; set; }

    [Required(ErrorMessage = "is required")]
    [Display(Name = "Website applicable on")]
    public string Website { get; set; }

    [Required(ErrorMessage = "is required")]
    [MinLength(10, ErrorMessage = "must be at least 10 characters.")]
    public string Description { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;


    public int UserId { get; set; }
    public User? User { get; set; }
    public List<Association> AllAssociations { get; set; } = new List<Association>();
}

Belt/BeltExam/Controllers/CouponController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using BeltExam.Models;

namespace BeltExam.Controllers;

[SessionCheck]
public class CouponController : Controller
{
    private readonly ILogger<CouponController> _logger;
    private MyContext db;

    public CouponController(ILogger<CouponController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }

// view all
    [HttpGet("coupons")]
    public IActionResult Index()
    {
        List<Coupon> allCoupons = db.Coupons.Include(coupon => coupon.AllAssociations)
        .Include(coupon => coupon.User).ToList();
        return View("AllCoupons", allCoupons);
    }


// new coupon form
    [HttpGet("coupons/new")]
    public IActionResult NewCoupon()
    {
        return View("NewCoupon");
    }


// create coupon
    [HttpPost("coupons/create")]
    public IActionResult CreateCoupon(Coupon newCoupon)
    {
        if (!ModelState.IsValid)
        {
            return View("NewCoupon");
        }

        newCoupon.UserId = (int)HttpContext.Session.GetInt32("UUID");

        db.Coupons.Add(newCoupon);
        db.SaveChanges();

        return RedirectToAction("Index");
    }


// use coupon
    [HttpPost("coupons/{id}")]
    public IActionResult UseCoupon(int id)
    {
        Association newAssociation = new Association()
        {
            UserId = HttpContext.Session.GetInt32("UUID"),
            CouponId = id
        };

        db.Associations.Add(newAssociation);

        db.SaveChanges();

        return RedirectToAction("Index");
    }


// privacy
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}


// session check
public class SessionCheckAttribute : ActionFilterAttribute
{
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        // Find the session, but remember it may be null so we need int?
        int? userId = context.HttpContext.Session.GetInt32("UUID");
        // Check to see if we got back null
        if (userId == null)
        {
            // Redirect to the Index page if there was nothing in session
            // "Home" here is referring to "HomeController", you can use any controller that is appropriate here
            context.Result = new RedirectToActionResult("Index", "User", null);
        }
    }
}

Belt/BeltExam/Views/Coupon/AllCoupons.cshtml
@model List<Coupon>

<h2 class="text-center">Welcome @Context.Session.GetString("Username")</h2>

<hr>

@foreach (Coupon coupon in Model)
{

        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@coupon.CouponCode</h5>
                <h6 class="card-subtitle mb-2 text-muted">@coupon.Website</h6>
                <p class="card-text">@coupon.Description</p>

                @{
                    if (Context.Session.GetInt32("UUID") == coupon?.UserId)
                    {
                        <h6 class="card-subtitle mb-2 text-muted">You posted this</h6>
                    } else
                    {
                        if (coupon.AllAssociations.Any(asso => asso.UserId == Context.Session.GetInt32("UUID")))
                        {
                            <h6 class="card-subtitle mb-2 text-muted">You used this</h6>
                        } else 
                        {
                            
                            <form asp-controller="Coupon" asp-action="UseCoupon" asp-route-id="@coupon.CouponId" method="POST">
                                <input type="submit" value="Use this coupon">
                            </form>
                        }
                    }
                }

                <h6 class="card-subtitle mb-2 text-muted">Posted by: @coupon.User?.Username</h6>
            </div>
        </div>
        <br>
        <br>

}

Belt/BeltExam/Views/Coupon/NewCoupon.cshtml
@model Coupon

<form asp-controller="Coupon" asp-action="CreateCoupon" method="POST" class="card-body bg-dark text-light rounded">

    <h2 class="text-primary text-decoration-underline fw-bold fs-1">Add a coupon</h2>

    <div class="form-group card-body">
        <label asp-for="CouponCode">Coupon Code</label>
        <span asp-validation-for="CouponCode" class="text-danger font-weight-bold"></span>
        <input asp-for="CouponCode" class="form-control"
                placeholder="please enter your coupon code...">
    </div>

    <div class="form-group card-body">
        <label asp-for="Website">Website applicable on</label>
        <span asp-validation-for="Website" class="text-danger font-weight-bold"></span>
        <input asp-for="Website" class="form-control"
            placeholder="please enter website name...">
    </div>

    <div class="form-group card-body">
        <label asp-for="Description">Description</label>
        <span asp-validation-for="Description" class="text-danger font-weight-bold"></span>
        <input asp-for="Description" class="form-control"
            placeholder="please enter your description...">
    </div>

    <br>

<input type="submit" value="Add coupon">

</form>